104corp/hydra

corp104/cmd/server/helper_cert.go
corp104/jwk/handler.go
corp104/oauth2/handler.go

Remove product information

---

corp104/cmd/server/handler_oauth2_factory.go
corp104/jwk/handler.go
corp104/jwk/handler_test.go
corp104/oauth2/handler.go
corp104/oauth2/handler_struct.go
corp104/oauth2/handler_test.go

- 新增用來加密 OAuth server metadata 的 JWKS，並在 server 啟動時輸出 Public Key 於 console
- 調整 metadata 的欄位

調整 Authorization Server Metadata 的返回結果為 signed_metadata

---

corp104/cmd/clients_create.go
corp104/cmd/url_implicit.go

1. 修改 client create 範例，以符合 public client 測試
2. 修改產生 oidc implicit flow 驗證網址的指令

修改 hydra url 指令以符合 client registration 調整

---

corp104/client/manager_sql.go
corp104/client/manager_test_helpers.go

1. 新增下列資料庫欄位
* software_id
* software_version
* id_token_signed_response_alg
* resource_sets

調整 clients sql，新增欄位

---

corp104/jwk/generator_ecdsa256.go

1. 調整 ECDSA256 的 generator，設定 alg 為 ES256

JWK 設定 alg 為 ES256

---

corp104/consent/handler.go
docker-compose-twoc.yml
docker-compose.yml

修改 login 接口的路徑

---

corp104/consent/handler.go
corp104/consent/handler_test.go
docker-compose-twoc.yml
docker-compose.yml

1. 登出後，刪除 web session 內 client_metadata 資訊
2. 設定 logout redirect url

Add logout redirect url to docker-compose

---

corp104/client/handler.go
corp104/client/sdk_test.go

補上 error 處理，將驗證失敗訊息返回 client 端

Fix update client 時，未處理 software_statement 驗證 error

---

mock-dep/login/mappings/company_create_failed.json
mock-dep/login/mappings/company_create_successful.json
mock-dep/login/mappings/login_successful_multiple_companies.json
mock-dep/login/mappings/login_successful_no_company.json
mock-dep/login/mappings/login_successful_one_company.json
mock-dep/login/mappings/multiple_companies.json
mock-dep/login/mappings/no_company_list.json
mock-dep/login/mappings/one_company.json

Add mock mapping data

---

mock-dep/login/mappings/email_is_available.json
mock-dep/login/mappings/email_is_not_available.json
mock-dep/login/mappings/get_id_by_email.json
mock-dep/login/mappings/get_info_by_code.json
mock-dep/login/mappings/get_password_mail_code.json
mock-dep/login/mappings/reset_password.json

Add mock data for reset password

---

corp104/client/handler.go
corp104/sdk/go/corp104/swagger/README.md
corp104/sdk/go/corp104/swagger/docs/OAuth2Api.md
corp104/sdk/go/corp104/swagger/o_auth2_api.go
docker-compose-twoc.yml
docker-compose.yml

1. 將 Client Registration 的 Path 從 `/register` 調整為 `/clients`

調整 Client Registration 的 Path

---

corp104/cmd/root.go
corp104/config/config.go
corp104/consent/handler.go
docker-compose-twoc.yml
docker-compose.yml

Extract reset password mail route to env

---

docker-compose-twoc.yml
docker-compose.yml

目的只有一個：把 docker-compose.yml 內的 mta 改成去拉 docker hub 的映象檔

Pull mta container from docker hub

---

corp104/consent/handler.go
docker-compose-twoc.yml
docker-compose.yml

Change route path for frontend

---

corp104/cmd/cli/handler_migrate.go

add resource migration

---

corp104/cmd/server/handler.go
corp104/cmd/server/handler_resource_factory.go
corp104/resource/handler.go

1. GET /resources 
2. GET /resources/{urn}

resources CORS 調整

---

corp104/oauth2/handler.go

Add issuer to ID Token claim aud

---

corp104/cmd/server/handler.go
corp104/cmd/server/helper_keys.go
scripts/deploy.sh

Offline JWK 載入順序：
1. 若有設定環境變數 `OFFLINE_PRIVATE_JWK`，則此 JWK 生效
2. 若不存在環境變數 `OFFLINE_PRIVATE_JWK`，則嘗試載入已存在 storage 中的 Offline JWK
3. 若 storage 中沒有已存在的 Offline JWK，則建立新的

調整 offline JWK 載入順序，將環境變數放在第一位

---

corp104/cmd/root.go
corp104/config/config.go
docker-compose-twoc.yml
docker-compose.yml

- 改 BYPASS_ROUTES 名字
- 將`AWS_ACCESS_KEY_ID` 跟 `AWS_SECRET_ACCESS_KEY ` 改吃環境變數

Rename bypass routes env

---

mock-dep/mappings/cors.json
mock-dep/mappings/email_is_available_available-email.json
mock-dep/mappings/email_is_not_available_alex.chang.json
mock-dep/mappings/email_is_not_available_evan.yen.json
mock-dep/mappings/get_id_by_email_alex.chang.json
mock-dep/mappings/get_id_by_email_andrea.williams.json
mock-dep/mappings/get_id_by_email_brandon.harmon.json
mock-dep/mappings/get_id_by_email_evan.yen.json
mock-dep/mappings/get_info_by_code_alex.chang.json
mock-dep/mappings/get_info_by_code_evan.yen.json
mock-dep/mappings/get_password_mail_code_alex.chang.json
mock-dep/mappings/get_password_mail_code_evan.yen.json
mock-dep/mappings/login_failed.json
mock-dep/mappings/login_successful_multiple_companies.json
mock-dep/mappings/login_successful_no_company.json
mock-dep/mappings/login_successful_one_company.json
mock-dep/mappings/login_successful_one_company_mobile.reg.json
mock-dep/mappings/login_successful_one_company_pc.reg.json
mock-dep/mappings/reset_password.json

將 mock api 的  CORS 表頭加上 everywhere

Change CORS header Access-Control-Allow-Origin to everywhere

---

corp104/consent/strategy_default.go
corp104/oauth2/handler.go

1. id token 加入 azp 以符合規格
2. 將 id token 的 signature  存入 web session

新增 azp 至 id token、新增 id_token_signature 至 web session

---

Dockerfile

調整 Dockerfile

---

mock-dep/mappings/get_id_by_email_mobile_reg.json
mock-dep/mappings/get_id_by_email_pc_reg.json

Add mock data for demo

---

Gopkg.lock
Gopkg.toml
corp104/cmd/server/handler_oauth2_factory.go
corp104/oauth2/handler.go
corp104/oauth2/session.go

增加 github.com/104corp/vip3-go-auth/vip3auth

Feature / Issue Access Token

---

corp104/client/handler.go
corp104/client/manager_wrapper.go
corp104/oauth2/handler.go
corp104/resource/manager.go
corp104/resource/manager_memory.go
corp104/resource/manager_sql.go

1. 調整 resource.SQLManager 及 resource.MemoryManager 的 `GetAllScopeNames(ctx)` 及 `GetResourceScopeMap(ctx)` 需傳入 Context
2. `GetAllScopeNames(ctx)` 及 `GetResourceScopeMap(ctx)` 其 resources 來源改為調用 `GetResources()` 取得

fix client 註冊 validation error

---

corp104/cmd/resources_commit.go
corp104/consent/strategy_default.go

將 `urn:104v3:entity:xx` 修改成 `urn:104:v3:entity`
> 可以先 approve，但請下週 demo 後再合併

Adjust urn name to fit spec

---

.travis.yml
scripts/deploy/deploy.sh
scripts/deploy/develope-task-definition.json

1. Travisci Using Ubuntu 16.04 to fix awscli SNIMissing 
2. Modify task-definition content
3. 在  task-definition  secure 中使用 ssm paramter
4. 固定使用 `entry_point` 為 ecs service 服務進入點 container name

Fix deploy error

---

scripts/deploy/develope-task-definition.json

修改 taskdefinition ssm parameter path

---

scripts/deploy/deploy.sh

* 由 cfn stack ( stack name 由 travis ECS_SERVICE_STACKNAME env var 決定 ) outputs 取得所需變數
* 增加 travisci var `ECS_SERVICE_STACKNAME`
* 移除 travisci var `ECS_SERVICE`

Using stack output

---

corp104/cmd/server/handler_oauth2_factory.go

- 調整 SPA Client Authentication Session 查驗功能開啟
**待 vip3-rms-web-app 將 auth-sdk 版本更新到 0.0.11 再合併**

調整 SPA Client Authentication Session 查驗功能開啟

---

corp104/cmd/server/handler_oauth2_factory.go
corp104/oauth2/handler.go
corp104/oauth2/handler_struct.go
corp104/oauth2/handler_test.go

修正 oauth server metadata 回傳的 JOSE 表頭的 typ 為 `server-metadata+jwt`

---

corp104/client/client.go
corp104/client/client_test.go
corp104/client/manager_0_sql_migrations_test.go
corp104/client/sdk_test.go
corp104/client/validator.go
corp104/client/validator_test.go
corp104/cmd/clients_put.go
corp104/cmd/root_test.go
corp104/jwk/sdk_test.go
corp104/oauth2/oauth2_auth_code_test.go
corp104/resource/sdk_test.go
mock-dep/mock_server.go

1. 允許 Client 註冊使用 `authorization_code` grant type
2. 調整 Client Metadata 的 [Validation rule](https://hackmd.io/O3wxLbr9RRaG6Rmzs--H-g#Validation4)
3. [client: rename grant type `authorize_code` to `authorization_code`](https://github.com/ory/hydra/pull/1191)

調整 Client Registration 以支援 `authorization_code` grant type
